name: Discord · Commit Notification

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get short commit hash
        id: commit
        run: echo "short=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

      # ===============================
      # 1️⃣ EMBED INFO COMMIT
      # ===============================
      - name: Send Commit Info (Embed)
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}

          embed-title: "🧩 New Commit: ${{ github.event.repository.name }}"
          embed-url: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          embed-thumbnail-url: "${{ secrets.COMMIT_THUMBNAIL_URL }}"

          embed-description: |
            > 📁 **Repo:** `${{ github.repository }}`
            > 🌿 **Branch:** `${{ github.ref_name }}`
            > 🔖 **Commit:** [`${{ steps.commit.outputs.short }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

          embed-fields: |
           [
             {
                "name": "📝 Message",
                "value": "> ${{ github.event.head_commit.message }}",
                "inline": false
             }
           ]
          embed-color: 14568502
          #embed-footer-icon-url: https://github.com/${{ github.actor }}.png
          #embed-footer-text: ${{ github.actor }}
          #embed-timestamp: ${{ github.event.head_commit.timestamp }}

      # ===============================
      # 2️⃣ EMBED MESSAGE COMMIT
      # ===============================
      - name: Send Commit Message (Embed)
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}

          embed-title: "📝 Message:"
          embed-description: |
            > ${{ github.event.head_commit.message }}

          embed-color: 14568502
          embed-footer-icon-url: https://github.com/${{ github.actor }}.png
          embed-footer-text: "${{ github.actor }} | C+${{ steps.commit.outputs.short }}"
          embed-timestamp: "${{ github.event.head_commit.timestamp }}"

