name: Discord · Commit Notification

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get short commit hash
        id: commit
        run: echo "short=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

      - name: Send commit notification to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}

          embed-title: "🧩 Commit Update: ${{ github.event.repository.name }}"
          embed-url: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          embed-thumbnail-url: "${{ secrets.COMMIT_THUMBNAIL_URL }}"

          # Identitas committer
          #embed-author-name: ${{ github.actor }}
          #embed-author-icon-url: https://github.com/${{ github.actor }}.png

          embed-description: |
            📁 **Repo:** `${{ github.repository }}`
            🌿 **Branch:** `${{ github.ref_name }}`
            🔖 **Commit:** [`${{ steps.commit.outputs.short }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            📝 **Message:**
            > **${{ github.event.head_commit.message }}**

          embed-color: 5793266
          embed-footer-icon-url: https://github.com/${{ github.actor }}.png
          embed-footer-text: ${{ github.actor }}
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
