name: Nightly Build

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Isi changelog Nightly (multi-line diperbolehkan)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore.jks

      - name: Build nightly APK
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleNightly

      - name: Update Changelog
        run: |
          NEW_LOG="## Changelog Nightly $(date -u +'%d/%m/%Y')\n${{ github.event.inputs.changelog }}"

          if [ -f NIGHTLY_CHANGELOG.md ]; then
            OLD_LOG=$(cat NIGHTLY_CHANGELOG.md)
            echo -e "$NEW_LOG\n\n$OLD_LOG" > NIGHTLY_CHANGELOG.md
          else
            echo -e "$NEW_LOG" > NIGHTLY_CHANGELOG.md
          fi

      - name: Get version
        id: version
        run: |
          TAG_DATE=$(date -u +"%Y%m%d")
          TITLE_DATE=$(date -u +"%d/%m/%Y")

          echo "version=nightly-$TAG_DATE" >> $GITHUB_OUTPUT
          echo "display_name=Nightly $TITLE_DATE" >> $GITHUB_OUTPUT

      - name: Create Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Hitori ${{ steps.version.outputs.display_name }}
          body_path: NIGHTLY_CHANGELOG.md
          prerelease: true
          files: |
            app/build/outputs/apk/nightly/app-nightly.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up keystore
        if: always()
        run: rm -f keystore.jks
